package interfaces;

import javax.swing.DefaultListModel;

public class VentaPanelAdmin extends javax.swing.JPanel {

    /**
     * Creates new form VentaPanelAdmin
     */
    public VentaPanelAdmin() {
        initComponents();
        jListProductos.setEnabled(false);

    }

    public void setjLabelCorreo(String txt) {
        jLabelCorreoValor.setText(txt);
    }

    public void setjLabelNombre(String txt) {
        jLabelNombreValor.setText(txt);
    }

    public void setjLabelPrecio(double precio) {
        jLabelPrecioValor.setText(String.valueOf(precio));
    }

    public void setjLabelFecha(String txt) {
        jLabelFechaValor.setText(txt);
    }

    public void setjListProductos(String[] txts) {
        DefaultListModel listModel = new DefaultListModel();
        for (int i = 0; i < txts.length; i++) {
            listModel.addElement(txts[i]);
        }
        jListProductos.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneProductos = new javax.swing.JScrollPane();
        jListProductos = new javax.swing.JList<>();
        jLabelCorreo = new javax.swing.JLabel();
        jLabelCorreoValor = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelPrecioValor = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelNombreValor = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelFechaValor = new javax.swing.JLabel();

        jListProductos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jListProductos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListProductosMouseClicked(evt);
            }
        });
        jScrollPaneProductos.setViewportView(jListProductos);

        jLabelCorreo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCorreo.setText("Correo electrónico:");

        jLabelCorreoValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCorreoValor.setText("Correo electrónico");

        jLabelPrecio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPrecio.setText("Precio total:");

        jLabelPrecioValor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelPrecioValor.setText("pr");

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");

        jLabelNombreValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNombreValor.setText("Correo electrónico");

        jLabelFecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelFecha.setText("Fecha de venta:");

        jLabelFechaValor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelFechaValor.setText("pr");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCorreo)
                    .addComponent(jScrollPaneProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPrecio)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPrecioValor, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelNombre)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFechaValor, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelNombreValor, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCorreoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPaneProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabelCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCorreoValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNombreValor)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrecio)
                    .addComponent(jLabelPrecioValor))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha)
                    .addComponent(jLabelFechaValor))
                .addContainerGap(121, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jListProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProductosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListProductosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelCorreoValor;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelFechaValor;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombreValor;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelPrecioValor;
    private javax.swing.JList<String> jListProductos;
    private javax.swing.JScrollPane jScrollPaneProductos;
    // End of variables declaration//GEN-END:variables
}
